re01/contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact-us/', views.contact_us, name='contact_us'),

]

re01/core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('/blog', views.blog, name='blog'),
    path('/about', views.about, name='about')
]

re01/properties/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sell/', views.sell, name='sell'),
    path('luxury-estate/', views.luxury_estate, name='luxury_estate'),
    path('oceanfront-retreats/', views.oceanfront_retreats, name='oceanfront_retreats'),
    path('urban-living/', views.urban_living, name='urban_living'),
    path('countryside_escapes/', views.countryside_escapes, name='countryside_escapes'),
    path('property-search/', views.property_search, name='property_search'),

]

re01/re01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('properties/', include('properties.urls')),
    path('contact/', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

re01/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('register/',views.register,name='register'),
    path('logout/', views.logout_view, name='logout'),
]

re01/contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    property_id = models.BigIntegerField(blank=True)
    message = models.TextField()

    def __str__(self):
        return self.name

re01/core/models.py
from django.db import models

# Create your models here.

re01/properties/models.py
from django.db import models


# Define choices for property categories
PROPERTY_CATEGORIES = (
    ('luxury', 'Luxury Estate'),
    ('oceanfront', 'Oceanfront Retreats'),
    ('urban', 'Urban Living Gems'),
    ('countryside', 'Countryside Escapes'),
)


class Property(models.Model):
    id = models.AutoField(blank=False, primary_key=True)
    property_title = models.CharField(max_length=200)
    property_description = models.TextField()
    property_type = models.CharField(max_length=50)
    property_category = models.CharField(max_length=20, choices=PROPERTY_CATEGORIES, default='luxury')
    property_price = models.DecimalField(max_digits=10, decimal_places=2)
    property_location = models.CharField(max_length=100)
    property_features = models.TextField(blank=True, null=True)
    seller_name = models.CharField(max_length=100)
    seller_email = models.EmailField()
    seller_phone = models.CharField(max_length=15)
    property_images = models.ImageField(upload_to='property_images/', blank=True, null=True)

    def __str__(self):
        return self.property_title

re01/users/models.py
from django.db import models


# Create your models here.
class Userregistration(models.Model):
    id=models.AutoField(blank=False,primary_key=True)
    username = models.CharField(max_length=50,blank=False)
    email = models.EmailField(max_length=50,blank=False)
    password = models.CharField(max_length=20)
    repassword = models.CharField(max_length=20)

    def __str__(self):
        return self.username

re01/contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email',  'property_id', 'message']

re01/properties/forms.py
from django import forms
from .models import Property


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        field = "__all__"
        exclude = ["id"]

re01/users/forms.py
from django import forms
from .models import Userregistration


class UserRegForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    repassword = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Userregistration
        fields = ['username', 'email', 'password', 'repassword']

re01/contact/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import ContactForm



def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            # You can add a success message or redirect to a thank-you page here
            return render(request, 'contact/thank.html')
    else:
        form = ContactForm()

    return render(request, 'contact/contact_us.html', {'form': form})

re01/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.

def homepage(request):
    return render(request, 'core/index.html')


def blog(request):
    return render(request, 'core/blog.html')


def about(request):
    return render(request, 'core/about.html')

re01/properties/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Property
from .forms import PropertyForm
from django.db.models import Q



def sell(request):
    form = PropertyForm(request.POST, request.FILES)
    if request.method == "POST":

        print('inside post')
        if form.is_valid():
            form.save()
            return render(request, 'properties/success.html')
    # else:
    #     form = UserRegForm()
    return render(request, 'properties/sell.html', {'form': form})



def luxury_estate(request):
    properties = Property.objects.filter(property_category='luxury')
    return render(request, 'properties/property_list.html', {'properties': properties})



def oceanfront_retreats(request):
    properties = Property.objects.filter(property_category='oceanfront')
    return render(request, 'properties/property_list.html', {'properties': properties})


def urban_living(request):
    properties = Property.objects.filter(property_category='urban')
    return render(request, 'properties/property_list.html', {'properties': properties})


def countryside_escapes(request):
    properties = Property.objects.filter(property_category='countryside')
    return render(request, 'properties/property_list.html', {'properties': properties})


def property_search(request):
    search_query = request.GET.get('search_query', '')
    location_filter = request.GET.get('location', '')
    category_filter = request.GET.get('category', '')
    features_filter = request.GET.get('features', '')

    # Use Q objects to perform an OR search across multiple fields
    properties = Property.objects.filter(
        Q(property_title__icontains=search_query) |
        Q(property_location__icontains=search_query) |
        Q(property_category__icontains=search_query) |
        Q(property_features__icontains=search_query)
    )

    return render(request, 'properties/search_results.html', {'properties': properties, 'search_query': search_query})

re01/users/views.py
from django.db.models import Q
from django.db.models.sql import AND
from django.shortcuts import render
from .models import Userregistration
from .forms import UserRegForm
from django.contrib.auth import logout
from django.shortcuts import redirect


def login_page(request):
    context = {'message': 'Invalid Credentials......'}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        data = Userregistration.objects.filter(Q(username=username), Q(password=password))
        if data:
            return render(request, 'core/index.html')
        else:
            return render(request, 'users/login_page.html', context)
    return render(request, 'users/login_page.html')


def register(request):
    form = UserRegForm(request.POST)
    if request.method == "POST":

        print('inside post')
        if form.is_valid():
            form.save()
            return render(request, 'core/index.html')
    # else:
    #     form = UserRegForm()
    return render(request, 'users/register.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('homepage')  # Redirect to your desired page after logout

re01/contact/templates/contact/contact_us.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div style="max-width: 400px; margin: 50px auto 20px auto; padding: 20px; border: 1px solid #ccc; border-radius: 5px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2); background-color: #fff; text-align: center;">

    <h1> Contact Us </h1>

    <form method="POST" style="margin-top: 20px; display: inline-block; text-align: left;">

        {% csrf_token %}

        <div style="text-align: left;">
            <label for="id_name" style="font-weight: bold;">Name:</label><br>
            {{ form.name }}
            <br>

            <label for="id_email" style="font-weight: bold;">Email:</label><br>
            {{ form.email }}
            <br>
            <label for="" style="font-weight: bold;">Property ID (optional):</label><br>
            {{ form.property_id }}
            <br>

            <label for="id_message" style="font-weight: bold;">Message:</label><br>
            {{ form.message }}
            <br>

        </div>

        <div style="text-align: center;">
            <input type="submit" value="Submit" style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; margin-top: 20px;">
        </div>

    </form>

</div>
{% endblock %}

re01/contact/templates/contact/thank.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div style="display: flex; justify-content: center; min-height: 100vh;">
  <div style="background-color: #f2f2f2; padding: 20px; border: 1px solid #ccc; border-radius: 5px; text-align: center; max-width: 400px; max-height: 300px; margin-top: 40px;">
    <p><b>Thank you for reaching out to us! </b><br> Your inquiry has been successfully received. One of our dedicated agents will review your message and get back to you as soon as possible. We appreciate your interest in our services and look forward to assisting you. In the meantime, feel free to explore our website for more information about our offerings.</p>
  </div>
</div>
{% endblock %}

re01/core/templates/core/about.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
 <header class="bg-primary text-light py-5">
        <div class="container text-center">
            <h1 class="display-4">About Us</h1>
        </div>
    </header>

    <main class="container my-5">
        <section>
            <h2>Our Story</h2>
            <p>
                Welcome to Your Real Estate Company, where we turn your property dreams into reality. Founded in 20XX, we have been dedicated to providing top-notch real estate services
                to our valued clients for over a decade.
            </p>
            <p>
                Our journey started with a vision: to create a modern and innovative real estate agency that offers personalized solutions to meet the unique needs of each client. Today,
                that vision is a reality.
            </p>
        </section>

        <section class="mt-5">
            <h2>Our Mission</h2>
            <p>
                At Your Real Estate Company, our mission is simple yet powerful: to help you find your perfect home or investment property while ensuring a smooth and stress-free
                experience. We are committed to delivering exceptional service, honest advice, and expert guidance throughout your real estate journey.
            </p>
            <p>
                Whether you are buying, selling, renting, or investing, our team of dedicated professionals is here to support you every step of the way. Your satisfaction is our ultimate
                goal, and we take pride in exceeding your expectations.
            </p>
        </section>
    </main>
{% endblock %}

re01/core/templates/core/base.html
{% load static %}
 <!-- Add this line to load user context -->

<!DOCTYPE html>
<html lang="en">
<head>
    <title>World's best real estate solution</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid px-5">
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/lease.gif' %}" alt="logo" style="width: 50px; height: 50px; display: inline-block;">
                <h1 style="font-family: 'Pacifico', cursive; font-size: 32px; display: inline-block;">Bhumi Sankalpa</h1>
            </a>
            <form class="d-flex justify-content-center mx-2" action="{% url 'property_search' %}" method="GET">
    <input class="form-control me-2" type="text" name="search_query"
           placeholder="Search by Location, Category, Features..." aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>


            <!-- ... (previous HTML code) ... -->

<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="signInDropdown" role="button"
           data-bs-toggle="dropdown" aria-expanded="false">
            <img
                src="https://static-assets-web.flixcart.com/batman-returns/batman-returns/p/images/profile-815786.svg"
                alt="Sign in" class="-dOa_b L_FVxe" width="24" height="24">
            {% if user.is_authenticated %}
                <span class="_1sLnDu">Logout</span>
            {% else %}
                <span class="_1sLnDu">Sign in</span>
            {% endif %}
        </a>
        <ul class="dropdown-menu" aria-labelledby="signInDropdown">
            {% if user.is_authenticated %}
                <li>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li>
                    <a class="dropdown-item" href="{% url 'register' %}">New Customer? Sign Up</a>
                </li>
                <li>
                    <a class="dropdown-item text-dark" href="{% url 'login' %}">My Profile</a>
                </li>
            {% endif %}
        </ul>
    </li>

<!-- ... (remaining HTML code) ... -->

            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>
        </div>
    </nav>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav w-100 d-flex flex-row justify-content-around">
                    <li class="nav-item flex-fill">
                        <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown flex-fill">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Explore
                        </a>
                        <ul class="dropdown-menu">
                            <!-- Explore dropdown items -->
                            <li><a class="dropdown-item" href="{% url 'homepage' %}#Features">Buy</a></li>
                            <li><a class="dropdown-item" href="{% url 'homepage' %}#Features">Rent</a></li>
                            <li><a class="dropdown-item" href="{% url 'sell' %}">Sell</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown flex-fill">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Featured
                        </a>
                        <ul class="dropdown-menu">
                            <!-- Featured dropdown items -->
                            <li><a class="dropdown-item" href="{% url 'luxury_estate' %}">Luxury Estates</a></li>
                            <li><a class="dropdown-item" href="{% url 'oceanfront_retreats' %}">Oceanfront Retreats</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'urban_living' %}">Urban Living Gems</a></li>
                            <li><a class="dropdown-item" href="{% url 'countryside_escapes' %}">Countryside Escapes</a>
                            </li>
                            <li><a class="dropdown-item" href="#">Investment Opportunities</a></li>
                            <li><a class="dropdown-item" href="#">Unique Architecture</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown flex-fill">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Services
                        </a>
                        <ul class="dropdown-menu">
                            <!-- Services dropdown items -->
                            <li><a class="dropdown-item" href="#">Property Insights</a></li>
                            <li><a class="dropdown-item" href="#">Personalized Consultations</a></li>
                            <li><a class="dropdown-item" href="#">Virtual Tours</a></li>
                            <li><a class="dropdown-item" href="#">Home Staging & Design</a></li>
                            <li><a class="dropdown-item" href="#">Property Management</a></li>
                            <li><a class="dropdown-item" href="#">Investment Analysis</a></li>
                            <li><a class="dropdown-item" href="#">Sustainable Living</a></li>
                        </ul>
                    </li>
                    <li class="nav-item flex-fill">
                        <a class="nav-link" href="{% url 'blog' %}">Blog</a>
                    </li>
                    <li class="nav-item flex-fill">
                        <a class="nav-link" href="{% url 'contact_us' %}">Contact</a>
                    </li>
                    <li class="nav-item flex-fill">
                        <a class="nav-link" href="#">
                            <img src="{% static 'images/bookmark.png' %}" alt="Icon Bookmark" width="20" height="20"
                                 class="d-inline-block align-text-top">
                            Saved Properties
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="content">
    {% block content %}
    {% endblock %}
</div>
<footer class="py-3">
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
                </a>
                <span class="text-muted">© 2021 Bhumi Sankalpa, Inc</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-muted" href="#"><img src="{% static 'images/twitter.png' %}"
                                                                     alt="Icon Bookmark" width="20" height="20"
                                                                     class="d-inline-block align-text-top"></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><img src="{% static 'images/instagram.png' %}"
                                                                     alt="Icon Bookmark" width="20" height="20"
                                                                     class="d-inline-block align-text-top"></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><img src="{% static 'images/facebook.png' %}"
                                                                     alt="Icon Bookmark" width="20" height="20"
                                                                     class="d-inline-block align-text-top"></a></li>
            </ul>
        </footer>
    </div>
</footer>
</body>
</html>

re01/core/templates/core/blog.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

<header class="container mt-5">
        <h1 class="display-4">Modern Real Estate Trends</h1>
        <p>Posted by John Doe | May 15, 2023</p>
    </header>

    <main class="container my-5">
        <article>
            <img src="{% static 'images/img_3.png' %}" alt="Modern Real Estate Trends" class="img-fluid rounded">
            <p class="lead mt-3">
                In today's rapidly changing real estate market, staying up-to-date with the latest trends and innovations is essential for both buyers and sellers.
            </p>
            <p>
                Here are some of the modern real estate trends that are reshaping the industry:
            </p>
            <h2>1. Smart Homes</h2>
            <p>
                The rise of smart home technology has revolutionized the way we live. Modern homebuyers are increasingly looking for properties equipped with smart features such as
                automated lighting, security systems, and energy-efficient appliances.
            </p>
            <h2>2. Sustainable Living</h2>
            <p>
                Sustainability is no longer a buzzword—it's a way of life. Green building practices, energy-efficient homes, and eco-friendly communities are in high demand.
                Buyers are not only looking for cost savings but also for homes that align with their environmental values.
            </p>
            <h2>3. Virtual Tours</h2>
            <p>
                The COVID-19 pandemic accelerated the adoption of virtual tours and 3D walkthroughs. Buyers can now explore properties from the comfort of their homes, making the
                homebuying process more convenient and efficient.
            </p>
            <h2>4. Urbanization</h2>
            <p>
                The trend towards urban living continues, with young professionals and empty nesters seeking homes in walkable neighborhoods with access to amenities, dining, and
                cultural attractions.
            </p>
            <h2>5. Co-living Spaces</h2>
            <p>
                Co-living arrangements, where multiple individuals or families share communal spaces, are gaining popularity in urban areas. This trend fosters a sense of community and
                reduces living costs.
            </p>
            <p>
                As the real estate landscape evolves, it's essential to work with professionals who understand these trends and can help you navigate the market successfully.
            </p>
        </article>
    </main>
{% endblock %}

re01/properties/templates/properties/property_list.html
{% extends "core/base.html" %}
{% block content %}
<div class="container my-3">
    <h1 class="my-4 text-center" id="Features">{{ category }} Properties</h1>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for property in properties %}
            <div class="col">
                <div class="card shadow-sm">
                    <!-- Add your card image here -->
                    <img src="https://source.unsplash.com/1600x900/?beautiful house" alt="img home">
                    <div class="card-body">
                        <h2 class="card-title">{{ property.property_title }} #{{ property.id }}</h2>
                        <p class="card-text">{{ property.property_description }}</p>
                        <p>Property Type: {{ property.property_type }}</p>
                        <p>Price: ${{ property.property_price }}</p>
                        <p>Location: {{ property.property_location }}</p>
                        {% if property.property_features %}
                            <p>Additional Features: {{ property.property_features }}</p>
                        {% endif %}
                        <p>Seller: {{ property.seller_name }}</p>
                        <div class="btn-group"> For more details &nbsp; &nbsp;
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'contact_us' %}">Contact Us</a></button>

                </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

re01/properties/templates/properties/search_results.html
{% extends "core/base.html" %}
{% block content %}
<div class="container my-3">
    <h1 class="my-4 text-center">Search Results for "{{ search_query }}"</h1>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for property in properties %}
            <div class="col">
                <div class="card shadow-sm">
                    <!-- Display property details here -->
                    <img src="https://source.unsplash.com/1600x900/?beautiful house" alt="img home">
                    <div class="card-body">
                        <h2 class="card-title">{{ property.property_title }} #{{property.id}}</h2>
                        <p class="card-text">{{ property.property_description }}</p>
                        <p>Property Type: {{ property.property_type }}</p>
                        <p>Price: ${{ property.property_price }}</p>
                        <p>Location: {{ property.property_location }}</p>
                        {% if property.property_features %}
                            <p>Additional Features: {{ property.property_features }}</p>
                        {% endif %}
                        <p>Seller: {{ property.seller_name }}</p>
                        <div class="btn-group"> For more details &nbsp; &nbsp;
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'contact_us' %}">Contact Us</a></button>

                </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col">
                <p style="text-align: center;">No properties match your search criteria.</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

re01/properties/templates/properties/sell.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div style="max-width: 400px; margin: 50px auto 20px auto; padding: 20px; border: 1px solid #ccc; border-radius: 5px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2); background-color: #fff; text-align: center;">

    <h1> Sell Your Property</h1>

    <form method="POST" style="margin-top: 20px; display: inline-block; text-align: left;">

        {% csrf_token %}

        <div style="text-align: left;">
            <label  style="font-weight: bold;">Property Title:</label><br>
            {{ form.property_title }}
            <br>

            <label  style="font-weight: bold;">Property Description:</label><br>
            {{ form.property_description }}
            <br>

            <label  style="font-weight: bold;">Property Type:</label><br>
            {{ form.property_type }}
            <br>

            <label  style="font-weight: bold;">Property Category:</label><br>
            {{ form.property_category }}
            <br>
            <label  style="font-weight: bold;">Property Price:</label><br>
            {{ form.property_price }}
            <br>
            <label  style="font-weight: bold;">City:</label><br>
            {{ form.property_location }}
            <br>
            <label  style="font-weight: bold;">Property Features:</label><br>
            {{ form.property_features }}
            <br>
            <label  style="font-weight: bold;">Seller Name:</label><br>
            {{ form.seller_name }}
            <br>
            <label  style="font-weight: bold;">Seller Email:</label><br>
            {{ form.seller_email }}
            <br>
            <label  style="font-weight: bold;">Seller Phone:</label><br>
            {{ form.seller_phone }}
            <br>
            <label  style="font-weight: bold;">Property Images:</label><br>
            {{ form.property_images }}
            <br>

        </div>

        <div style="text-align: center;">
            <input type="submit" value="Submit" style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; margin-top: 20px;">
        </div>

    </form>

</div>
{% endblock %}

re01/properties/templates/properties/success.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<h1 style="text-align:center;">Added to list.</h1>
{% endblock %}

re01/users/templates/users/loginsuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Login Success</h1>
</body>
</html>

re01/users/templates/users/register.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div style="max-width: 400px; margin: 50px auto 20px auto; padding: 20px; border: 1px solid #ccc; border-radius: 5px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2); background-color: #fff; text-align: center;">

    <h1> SIGN UP</h1>

    <form method="POST" style="margin-top: 20px; display: inline-block; text-align: left;">

        {% csrf_token %}

        <div style="text-align: left;">
            <label for="id_username" style="font-weight: bold;">Username:</label><br>
            {{ form.username }}
            <br>

            <label for="id_email" style="font-weight: bold;">Email:</label><br>
            {{ form.email }}
            <br>

            <label for="id_password" style="font-weight: bold;">Password:</label><br>
            {{ form.password }}
            <br>

            <label for="id_repassword" style="font-weight: bold;">Confirm Password:</label><br>
            {{ form.repassword }}
            <br>
        </div>

        <div style="text-align: center;">
            <input type="submit" value="Submit" style="background-color: #007bff; color: #fff; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; margin-top: 20px;">
        </div>

    </form>

</div>
{% endblock %}

re01/users/templates/users/regsuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>User Registered Success</h1>
<button><a href="{% url 'login' %}">Login</a></button>
</body>
</html>